### ISSUE TITLE
Add module to opentofu registry 

### ISSUE THREAD

**Issue by nitrocode** [chime/terraform-aws-alternat#100]
## context
This is to have a 1:1 with the terraform registry by adding this to the opentofu registry

https://github.com/opentofu/registry/?tab=readme-ov-file#adding-providers-modules-or-gpg-keys-to-the-opentofu-registry

https://opentofu.org/registry/

## references
- similar to #84
- submitted module here https://github.com/opentofu/registry/issues/510
- closed when this merges https://github.com/opentofu/registry/pull/511

**Comment by bwhaley** [comment]
Submitted: https://github.com/opentofu/registry/issues/518

**Comment by nitrocode** [comment]
I beat you to it 😉
