### ISSUE TITLE
Clarify the need for lambda VPC endpoint in the documentation

### ISSUE THREAD

**Issue by BrainsDevOps** [chime/terraform-aws-alternat#110]
Forgive me if this has already been asked but I haven't found the answer in the documentation or in other issues.

I understand the need for the EC2 VPC endpoint to replace the routes in the route table when there are connectivity issues. But I don't see that the lambda VPC endpoint is needed for this. If I'm correct, the lambda endpoint is used for testing purposes only, Could you please confirm if this is the case?

I would be happy open a PR to update the documentation if thats the case. Maybe its not a big saving, but having an extra VPCe in 4 AZs could represent around 30$/month.

Thank you

**Comment by bwhaley** [comment]
Yes, that's true, I can't see think of any reason why a Lambda endpoint would be necessary. If connectivity is down through the NAT gateway, the Lambda would detect the issue and send requests to the EC2 API to switch the route. The Lambda API wouldn't be called. I don't see any reason why it's strictly necessary.

PR welcome!

**Comment by BrainsDevOps** [comment]
I was trying to read the tests in more detail to update the documentation, but even in the tests I've got the impression that the lambda VPC endpoint is not used at all. Should the PR go in the direction of removing the VPC endpoint altogether instead of updating the documentation?

Cheers

**Comment by bwhaley** [comment]
Yeah, let's just remove it. This will be marked as a backward incompatible release, which I generally avoid, but since we don't need an endpoint to Lambda then we may as well remove it now rather than later.

We should strip out all the Lambda endpoint stuff from `main.tf`, `variables.tf`, and the README. Not sure if it's mentioned anywhere else.
