### ISSUE TITLE
No logs emitted by lambda

### ISSUE THREAD

**Issue by paymog** [chime/terraform-aws-alternat#114]
I've deployed this with great success! I tried manually messing around with the security groups to force a route replacement. However, when I check the cloudwatch logs for the lambda all I see are requests starts and ends like so

<img width="1664" alt="image" src="https://github.com/user-attachments/assets/430c6bd6-92f1-402e-baab-9841667a8bd0">

Is there special config I need to enable when creating the Alternat to get lambda logs to populate correctly in cloudwatch?

**Comment by bwhaley** [comment]
I'm glad to hear that you were able to deploy Alternat and you're having success with it!

When Alternat is healthy and there are no issues, it doesn't emit any logs, so this is expected. It will log messages when it switches over the route table. You can simulate this by forcing Alternat to switch over the route table, for example by putting updating the Security Group for the Alternat EC2 instances to not accept any traffic. This will cause the connectivity check to fail and the route to switch over, which you should see reflected in the logs.
