### ISSUE TITLE
amazon linux 2 deprecated in favor of amazon linux 2023

### ISSUE THREAD

**Issue by nitrocode** [chime/terraform-aws-alternat#81]
It seems that AL2023 will be superseding AL2

Is it on the roadmap to switch 2023 ?

https://aws.amazon.com/amazon-linux-2/faqs/

> Q. When will support for Amazon Linux 2 end?
> 
> Amazon Linux 2 end of support date (End of Life, or EOL) has been extended by two years from 2023-06-30 to 2025-06-30 to provide customers with ample time to migrate to the next version.

https://docs.aws.amazon.com/linux/al2023/ug/compare-with-al2.html

**Comment by bwhaley** [comment]
Sure, it's on the roadmap! We'd welcome the contribution if you're interested in working on it.

**Comment by cgill27** [comment]
I have not tested the change yet, but below is what you'd change to start using Amazon Linux 2023 x86_64, available from the AWS parameter store:

Remove old data source completely:
https://github.com/1debit/alternat/blob/main/modules/terraform-aws-alternat/main.tf#L151

Add new data source:
`data "aws_ssm_parameter" "amazon_linux_ami" {
  name = "/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64"
}`

Change:
https://github.com/1debit/alternat/blob/main/modules/terraform-aws-alternat/main.tf#L223
Change to:
`image_id = var.nat_ami == "" ? data.aws_ssm_parameter.amazon_linux_ami.value : var.nat_ami`

This will atleast get the AMI changed to 2023, not sure if there are other userdata changes that maybe required.

**Comment by nitrocode** [comment]
Looks like the competing fck-nat uses the latest amazon Linux 2023. Mentioned for inspiration.

https://github.com/AndrewGuenther/fck-nat
